JuliaSmoothOptimizers/HSL.jl

- README.md
- src/hsl_ma57.jl
- test/test_ma57.jl
had some trouble merging / adding my edits (hence multiple commits), but i...
...started adding documentation for ma57 including:
- `ma57_solve`
- `ma57_factorize`, `ma57_factorise`
- `ma57_get_factors`
- `Ma57`
...to-do:
- `ma57_alter_d`
> adding documentation for ma57

- deps/build.jl
> Fix missing command on Dominique's patch

- src/hsl_ma57.jl
- test/test_ma57.jl
> interface for non-default control parameters

- deps/build.jl
> update sha for HSL_MA97 2.6.0

- .gitignore
- README.md
- deps/build.jl
- deps/build_hsl_ma57.jl
- deps/build_hsl_ma97.jl
- deps/downloads/README.md
- test/test_ma57_patch.jl
> Allow custom path for HSL archives

- src/hsl_ma57.jl
I also found that : https://github.com/optimizers/nlpy/blob/master/nlpy/linalg/src/_pyma57.c#L91-L94
> Add sqd option for MA57

- .github/workflows/ci.yml
- docs/make.jl
These changes were made automatically, please check before merging.
> [AUTO] Change master to main

- test/Jenkinsfile
- test/run_tests.sh
- test/send_gist_url.jl
> Jenkins configuration for unit tests

- src/HSL.jl
> expose libopenblas and libmetis to linker

- test/Jenkinsfile
- test/send_gist_url.jl
Unit tests run with SunGrid Engine and the build log will be included in the gist.
> run unit tests with SGE + build log in gist

- README.md
- deps/build.jl
- deps/build_hsl_ma57.jl
- deps/build_hsl_ma97.jl
This is just a clean rebase of #66 to get rid of the merge commits.
> Bjack205 ma97 v2.7

- src/hsl_ma97.jl
- test/test_ma97.jl
> Bjack205 concrete refs

- .github/workflows/Documentation.yml
- docs/Project.toml
- src/HSL.jl
> build docs on GHA VM

- docs/make.jl
- docs/src/index.md
- docs/src/reference.md
- docs/src/tutorial.md
Following https://github.com/JuliaSmoothOptimizers/HSL.jl/pull/91 and #90 
A JSO compliant doc
> Refactor doc

- deps/build.jl
- deps/build_hsl_ma57.jl
- deps/build_hsl_ma97.jl
> Add -O3 option in build.jl

- Project.toml
- deps/build.jl
- src/HSL.jl
- test/runtests.jl
@tmigot It should solve your issue with DCISolver.jl.
> Drop binaryProvider

- deps/build.jl
I don't know if we can compile something on WIndows, but i'm sure that it doesn't work without this fix.
> Fix compilation script on Windows

- src/hsl_ma57.jl
- src/hsl_ma57_patch.jl
- src/hsl_ma97.jl
- src/mc21.jl
- test/test_hsl_ma57.jl
- test/test_hsl_ma57_patch.jl
- test/test_mc21.jl
> Use Cint and Cvoid everywhere

- Project.toml
- test/runtests.jl
- test/test_hsl_ma57.jl
- test/test_hsl_ma57_patch.jl
- test/test_hsl_ma97.jl
> Convert unit tests into TestSets

- deps/build.jl
The compilation script was not working on FreeBSD or Windows platforms.
It could still not work but It will help to support these platforms.
> Use Libdl.dlext

- deps/versions.jl
- src/kb07.jl
- test/test_kb07.jl
> [KB07] Add a Julia interface

- deps/versions.jl
- src/mc77.jl
- test/test_mc77.jl
It's probably the implementation of Daniel Ruiz.
> [MC77] Add a Julia interface

- deps/versions.jl
- gen/Project.toml
- gen/README.md
- gen/hsl.toml
- gen/rewriter.jl
- gen/wrapper.jl
@dpo 
I opened the PR as a draft to illustrate what we can do with Clang.jl.
I propose to merge the generator and after we can do PR for each generated interface.
`rewriter.jl` is used for the last commit. We have a neat result with it!
> Add a script to interface HSL packages with Clang.jl

- test/test_hsl_ma57_patch.jl
`ma57_alter_d` seems to not working :(
> Test ma57_alter_d

- deps/build.jl
- deps/versions.jl
> Improve the build system

- src/hsl_ma97.jl
I found a few errors in our `Ma97_info` and `Ma97_control` structures.
I removed them to use the structures generated by Clang.jl.
I also replaced all `ccall` by Julia wrappers.
> Remove all ccall in src/hsl_ma97.jl

- gen/analyzer.jl
- src/Fortran/eb22.jl
- src/Fortran/fd15.jl
- src/Fortran/ma49.jl
- src/Fortran/ma62.jl
- src/Fortran/mc36.jl
- src/Fortran/mc54.jl
- src/Fortran/mc55.jl
- src/Fortran/mc56.jl
- src/Fortran/me62.jl
- src/Fortran/mf36.jl
- src/Fortran/ym11.jl
@AndrewLister-STFC
I think that it's what suggested Nick about hidden arguments.
> Add hidden Fortran arguments in the wrappers

- gen/rewriter.jl
- src/C/hsl_ma48.jl
- src/C/hsl_ma57.jl
- src/C/hsl_ma77.jl
- src/C/hsl_ma86.jl
- src/C/hsl_ma87.jl
- src/C/hsl_ma97.jl
- src/C/hsl_mc64.jl
- src/C/hsl_mc68.jl
- src/C/hsl_mc78.jl
- src/C/hsl_mc79.jl
- src/C/hsl_mi20.jl
- src/C/hsl_mi28.jl
- src/hsl_ma97.jl
> Update the C wrappers

- .breakage/Project.toml
- .breakage/get_jso_users.jl
- .github/workflows/Breakage.yml
- copier-answers.jso.yml
Automated update using JSOBestieTemplate
> Update with JSOBestieTemplate for HSL
