JuliaSmoothOptimizers/HSL.jl

- deps/build.jl
- deps/build_hsl_ma57.jl
- src/HSL.jl
- test/runtests.jl
- test/test_ma57.jl
I've rebased `ma57` according to our discussion yesterday, and this pull request is against that branch to fix the build system.
There is also a fix on the tests because Julia `\` is not working with `SparseMatrixCSC{Float32,Int32}` (https://github.com/JuliaLang/julia/issues/30849).
> Updates MA57 to use new build and fix tests for Julia 1.1

- Project.toml
Following https://github.com/JuliaRegistries/Registrator.jl?installation_id=887100&setup_action=install#how-to-use I've allowed `Registrator` and `TagBot` on the organization.
After this is merged, I'll use the magic command to register HSL and
close #31
> Version 0.1.0

- .github/workflows/CI_M1.yml
- deps/build_hsl_ma57.jl
this is useful on Apple Silicon when compiling for x86_64,
among others, where HSL_FC = "gfortran -arch x86_64".
> allow compiler flags to be part of HSL_FC

- README.md
- src/hsl_ma57.jl
- test/test_ma57.jl
- test/test_ma57_patch.jl
- `ma57_factorize(ma57::Ma57)` is now  `ma57_factorize!(ma57::Ma57)`.
- `ma57_solve!` now requires a work vector.
- `ldiv!` has been removed, since its behaviour cannot be copied (in this case the 2-args `ldiv!` would have to allocate, and the 3-args `ldiv!` would erase the right-hand side, which is not the behaviour of the 3-args `div!` from LinearAlgebra).
This PR allows to remove the allocation of:
- 1 `Vector{Int32}` of size `ma57.n` at each `ma57_factorize!(ma57)` call,
- 1 `Vector{Int32}` of size `ma57.n` and 1 `Vector{Float}` `work` of size `ma57.n * size(b, 2)` at each `ma57_solve!(ma57, b, work)` call.
> Remove allocations from factorizations and solves

- src/HSL.jl
It's possible to do load a 32 bits BLAS (like MKL) before `using HSL` now.
> Use OpenBLAS32_jll only if a LP64 BLAS is not loaded

- src/hsl_ma97.jl
Use outer constructors for `Ma97_Info` and `Ma97_Control` to be able to use the default constructor with all the arguments of the structs.
The `Ma97` inner constructor is not modified since it uses all the arguments of the structure (and performs an additional check).
> Switch to outer constructor for control and info Ma97

- test/test_ma57_patch.jl
With Julia 1.8, `d2 = [diag(D, 1); 0]` returns a `SparseMatrixCSC`.
It was a `SparseVector` wih previous versions of Julia.
> Fix tests with the MA57 patch

- .github/workflows/CI_M1.yml
`codecov/codecov-action@v2` and `codecov/codecov-action@v3` use `files` whereas `codecov/codecov-action@v1` uses `file`.
> [CI_M1] file -> files

- Project.toml
The version `0.3.1` doesn't have `BinaryProvider` as dependency.
The version of `METIS4_jll` is also updated, `v400.0.300` has M1 artifacts.
> Release 0.3.1

- deps/build.jl
I have some issues when I switch between branches and recompile HSL softwares.
With this modification, `usr` folder and `deps.jl` file are removed when we build HSL.
It solved my issues.
> Clean deps folder when we recompile

- deps/build.jl
@tmigot, @geoffroyleconte and @AntoninKns sometimes observed the error
```julia
ERROR: LoadError: UndefVarError: ma57_coord not defined
```
https://github.com/JuliaSmoothOptimizers/HSL.jl/pull/129#issuecomment-1278104191 when they tested HSL.
The reason of this error is that HSL was already precompiled without MA57 and a
recompilation was not triggered when we build it.
This PR should fix the issue.
> Remove precompiled .ji files when we build HSL

- test/Jenkinsfile
This new Jenkinsfile is now completely generic. The new features are: 
1. No longer needed to specify a token manually. It is automatically set to `"$(module_name)_Test"` (i.e, HSLTest).
2. It is no longer **required** to have the `test/run_tests.sh` and the `test/send_gist_url` in the `test` subfolder.
2.1 If you still want to provide your own `test/run_tests.sh` script, the build will use the version found in the repository.
3. Unit tests will be available for all repositories of the JSO organization.
4.  Unit tests will run **automatically** on any change to the Pull Request.
For this repo, since the `test/send_gist_url.jl` has been modified from the default version found in [this repo](https://github.com/ProofOfConceptForJuliSmoothOptimizers/BenchmarkSetup), we should keep both files …
> generic jenkinsfile for unit tests that run automatically

- Project.toml
- deps/build.jl
METIS4_jll is now a shared library, we changed the `soname` such that it can coexist with `metis.$dlext` of `METIS_jll`.
https://github.com/JuliaPackaging/Yggdrasil/pull/5829
> Use the new version of METIS4_jll

- deps/build.jl
- deps/versions.jl
- src/HSL.jl
- test/runtests.jl
@dpo
- Add a function `getsha` to easily compute the SHA of new releases.
- Add `hsl_collection["coinhsl"]` in `deps/versions.jl`.
With this PR, `coinhsl` is automatically compiled with METIS_jll, and OpenBLAS32_jll / LBT_jll.
We use the most efficient optimization level `-03` like the other packages.
The user just needs to provide `ENV["HSL_ARCHIVES_PATH"]` such that we know where the `.zip` and `tar.gz` are located on the computer.
```julia
set_optimizer_attribute(model, "hsllib", HSL.libcoinhsl)
set_optimizer_attribute(model, "linear_solver", "ma27")
set_optimizer_attribute(model, "linear_solver", "ma86")
...
```
cc @odow @tmigot for `Ipopt.jl` and `NLPModelsIpopt.jl`
If a user only has `MA97` for instance, it's still possible to use it in Ipopt:
```julia
set_optimizer_attribute(model, …
```
> Add coinhsl

- deps/versions.jl
If the `configure` of `hsl_ma97` is similar to the `configure` of `coinhsl`, we should have missing BLAS/LAPACK symbols at runtime.
> Try HSL_MA97 2.7.2

- README.md
The instructions are all there, but they could make the `HSL_ARCHIVES_PATH` more explicit.
> [README] Refactor installation instructions

- deps/versions.jl
This PR adds version number and checksums for the 2022-11-09 `coinhsl` releases from HSL.
I have locally tested this version on a Linux (Redhat) system.
The build step works, `test HSL` runs without errors, and I was able to run sample problems with Ipopt as follows:
```julia
using HSL, JuMP, Ipopt
opt = optimizer_with_attributes(Ipopt.Optimizer, "linear_solver" => "ma27", "hsllib" => HSL.libcoinhsl)
opt = optimizer_with_attributes(Ipopt.Optimizer, "linear_solver" => "ma57", "hsllib" => HSL.libcoinhsl)
model = Model(opt)
@variable(model, x >= 0)
@objective(model, Min, x*x)
optimize!(model)
```
I did not find reference checksums from HSL, so the checksum values are ones I computed by running on a Linux (WSL) machine
* `sha256sum coinhsl-2022.11.09.zip`
* `sha256sum …
> Add 2022-11-09 coinhsl versions

- Project.toml
Prep for a new release.
I use HSL solvers in Ipopt via HSL.jl. Having a tagged version would make it much easier to manage that.
> Bump version --> v0.3.6

- src/kb07.jl
- src/mc21.jl
- src/mc77.jl
I also fixed an error in `mc77`, `a` is a `Ptr{$elty}` and not a `Ptr{Cint}`. I don't understand why It was working before...
> Use the ccall macro in kb07, mc21 and mc77

- Project.toml
- Use JuliaHSL and the precompiled version HSL_jll.jl
> Release 0.4.0

- gen/analyzer.jl
- src/Fortran/ma62.jl
- src/Fortran/me62.jl
https://community.intel.com/t5/Intel-Fortran-Compiler/Passing-array-of-strings-to-Fortran/m-p/767588
> Add an hidden argument in ccall for arrays of strings

- src/mc77.jl
- test/runtests.jl
- test/test_hsl_ma57.jl
- test/test_mc77.jl
@frapac @michel2323
I fixed many bugs in the Julia interface of `MC77`.
It should work fine now.
To solve a scaled linear system, you just need:
```julia
Dr, Dc = mc77(A_cpu, 0)
inv_Dr = Diagonal(1.0 ./ Dr)
inv_Dc = Diagonal(1.0 ./ Dc)
As = inv_Dr * A * inv_Dc
bs = inv_Dr * b
xs = As \ bs
x = inv_Dc * xs
```
I checked the algorithm and we should be able to port this scaling on GPU if it performs well.
> Fix the interface of MC77
